Fix: utils: use -o and -n to compare files instead of strings for crm_diff (bsc#1201312)
Fixes: <https://github.com/ClusterLabs/crmsh/issues/983>

When trying to run 'crm node standby' or online command and
when the cib being printed is too long and overflows MAX_ARG_STRLEN, exception raised like:
  OSError: [Errno 7] Argument list too long: '/bin/sh'

Use -o and -n of cib_diff to compare files instead of strings fix this issue